export interface Product {
  id: string;
  name: string;
  price: number;
  category: string;
}

export const products: Product[] = [
  { id: "p1", name: "Coffee - Regular", price: 2.50, category: "Beverages" },
  { id: "p2", name: "Coffee - Large", price: 3.50, category: "Beverages" },
  { id: "p3", name: "Espresso", price: 2.75, category: "Beverages" },
  { id: "p4", name: "Cappuccino", price: 4.25, category: "Beverages" },
  { id: "p5", name: "Latte", price: 4.50, category: "Beverages" },
  { id: "p6", name: "Tea - Regular", price: 2.00, category: "Beverages" },
  { id: "p7", name: "Tea - Herbal", price: 2.25, category: "Beverages" },
  { id: "p8", name: "Hot Chocolate", price: 3.75, category: "Beverages" },
  { id: "p9", name: "Iced Coffee", price: 3.75, category: "Beverages" },
  { id: "p10", name: "Iced Tea", price: 3.25, category: "Beverages" },
  { id: "p11", name: "Orange Juice", price: 3.00, category: "Beverages" },
  { id: "p12", name: "Apple Juice", price: 3.00, category: "Beverages" },
  { id: "p13", name: "Croissant", price: 2.95, category: "Bakery" },
  { id: "p14", name: "Bagel", price: 2.50, category: "Bakery" },
  { id: "p15", name: "Muffin - Blueberry", price: 3.25, category: "Bakery" },
  { id: "p16", name: "Muffin - Chocolate", price: 3.25, category: "Bakery" },
  { id: "p17", name: "Danish - Cheese", price: 3.50, category: "Bakery" },
  { id: "p18", name: "Danish - Fruit", price: 3.50, category: "Bakery" },
  { id: "p19", name: "Cookie - Chocolate Chip", price: 1.75, category: "Bakery" },
  { id: "p20", name: "Cookie - Oatmeal Raisin", price: 1.75, category: "Bakery" },
  { id: "p21", name: "Ham Sandwich", price: 6.95, category: "Sandwiches" },
  { id: "p22", name: "Turkey Sandwich", price: 6.95, category: "Sandwiches" },
  { id: "p23", name: "Veggie Sandwich", price: 5.95, category: "Sandwiches" },
  { id: "p24", name: "Tuna Sandwich", price: 6.50, category: "Sandwiches" },
  { id: "p25", name: "Chicken Salad Sandwich", price: 6.95, category: "Sandwiches" },
  { id: "p26", name: "BLT Sandwich", price: 7.25, category: "Sandwiches" },
  { id: "p27", name: "Club Sandwich", price: 8.50, category: "Sandwiches" },
  { id: "p28", name: "Caesar Salad", price: 7.95, category: "Salads" },
  { id: "p29", name: "Garden Salad", price: 6.95, category: "Salads" },
  { id: "p30", name: "Greek Salad", price: 8.50, category: "Salads" },
  { id: "p31", name: "Cobb Salad", price: 9.25, category: "Salads" },
  { id: "p32", name: "Chicken Soup", price: 4.95, category: "Soups" },
  { id: "p33", name: "Tomato Soup", price: 4.50, category: "Soups" },
  { id: "p34", name: "Vegetable Soup", price: 4.50, category: "Soups" },
  { id: "p35", name: "Clam Chowder", price: 5.50, category: "Soups" },
  { id: "p36", name: "Bottled Water", price: 1.50, category: "Beverages" },
  { id: "p37", name: "Sparkling Water", price: 2.00, category: "Beverages" },
  { id: "p38", name: "Soda - Small", price: 1.75, category: "Beverages" },
  { id: "p39", name: "Soda - Medium", price: 2.25, category: "Beverages" },
  { id: "p40", name: "Soda - Large", price: 2.75, category: "Beverages" },
  { id: "p41", name: "Cheesecake", price: 5.50, category: "Desserts" },
  { id: "p42", name: "Chocolate Cake", price: 5.25, category: "Desserts" },
  { id: "p43", name: "Apple Pie", price: 4.95, category: "Desserts" },
  { id: "p44", name: "Brownie", price: 2.95, category: "Desserts" },
  { id: "p45", name: "Ice Cream (2 scoops)", price: 3.95, category: "Desserts" },
  { id: "p46", name: "Fruit Cup", price: 3.50, category: "Snacks" },
  { id: "p47", name: "Yogurt Parfait", price: 4.25, category: "Snacks" },
  { id: "p48", name: "Potato Chips", price: 1.25, category: "Snacks" },
  { id: "p49", name: "Granola Bar", price: 1.95, category: "Snacks" },
  { id: "p50", name: "Fresh Fruit", price: 1.50, category: "Snacks" }
];